version: "3.8"

services:
  postgres_db:
    image: postgres:15-alpine
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: project_management
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d project_management"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  minio_storage:
    image: minio/minio:latest
    container_name: minio_storage
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001" # Bật giao diện web ở cổng 9001
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  backend_app:
    build: .
    container_name: backend_app
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres_db:5432/project_management
      - MINIO_ENDPOINT=http://minio_storage:9000
    depends_on:
      postgres_db:
        condition: service_healthy
      minio_storage:
        condition: service_healthy
    restart: on-failure

volumes:
  postgres_data:
  minio_data:
