spring:
  application:
    name: projectmanagement
  datasource:
    url: jdbc:mysql://localhost:3306/project_management?createDatabaseIfNotExist=true
    username: root
    password: 12345
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  jackson:
    property-naming-strategy: SNAKE_CASE
  mail:
    host: smtp.gmail.com
    port: 587
    username: tanh11704@gmail.com
    password: ohwk czxf pzvr lsbn
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: tru
            required: true

minio:
  endpoint: http://localhost:9000
  access-key: minioadmin
  secret-key: minioadmin
  bucket-name: project-management

jwt:
  secret-key: daf66e01593f61a15b857cf433aae03a005812b31234e149036bcc8dee755dbb
  expiration-ms: 900000 # 15 minutes
  refresh-expiration-ms: 604800000 # 7 days
